site_name: RTFM, please
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
#  - mkdocstrings:
#      handlers:
#        # See: https://mkdocstrings.github.io/python/usage/
#        python:
#          options:
#            docstring_style: sphinx
#markdown_extensions:
#  - markdown_include.include:
#      base_path: .
##  - admonition
##repo_url: https://github.com/so07/rtfm.git/
#repo_url: https://github.com/so07/rtfm/
#edit_uri: blob/main/

    #repo_url: https://github.com/so07/rtfm
    #edit_uri: blob/main/docs/docs/

